### ISSUE TITLE
Example is not type safe

### ISSUE THREAD

**Issue by gouldingken** [sasakiassociates/henshu#1]
This line from the readme example:

`<Henshu content={content} onChange={tree => setContent(tree)} editing={isEditing}>`

raises:

`TS2345: Argument of type 'StringMap' is not assignable to parameter of type 'SetStateAction<{ header: string; paragraph: string; }>'.   Type 'StringMap' is missing the following properties from type '{ header: string; paragraph: string; }': "header", "paragraph"`

**Comment by ericyoungberg** [comment]
Closed by 59789440fab406b09d6816be9e8774e1a70054b5
